AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create resources for Terraform state management.

Resources:
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: terraform-prod-dev-aws-infra
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: my-terraform-lock-table
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  S3BucketName:
    Description: Name of the S3 Bucket for Terraform state
    Value: !Ref TerraformStateBucket

  DynamoDBTableName:
    Description: Name of the DynamoDB table for Terraform state locking
    Value: !Ref DynamoDBTable